version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /simple_blog_engine/manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    volumes:
      - .:/blog_engine
