# Generated by Django 4.0.5 on 2022-06-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
